# Generated by Django 4.1.2 on 2022-11-01 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("initials", models.CharField(max_length=5)),
                (
                    "e_sports",
                    models.CharField(
                        choices=[
                            ("League of Legends", "Leagueoflegends"),
                            ("Overwatch", "Overwatch"),
                            ("Counter Strike", "Counterstrike"),
                            ("Valorant", "Valorant"),
                            ("Is not in a championship", "Default"),
                        ],
                        default="Is not in a championship",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
