# Generated by Django 4.1.2 on 2022-11-07 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="e_sports",
            new_name="e_sport",
        ),
    ]
