# Generated by Django 4.1.2 on 2022-11-01 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("championships", "0003_alter_championship_staff_owner_id"),
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="championship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="championships.championship",
            ),
        ),
    ]
