# Generated by Django 4.1.2 on 2022-11-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="balance",
        ),
    ]
