# Generated by Django 4.1.2 on 2022-11-07 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("users", "0002_remove_user_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="teams.team",
            ),
        ),
    ]
