# Generated by Django 4.1.2 on 2022-11-04 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("initial_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("team_1", models.CharField(max_length=120)),
                ("team_2", models.CharField(max_length=120)),
                ("winner", models.CharField(max_length=120)),
                ("total_value", models.FloatField()),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bet",
                        to="games.game",
                    ),
                ),
            ],
        ),
    ]
