# Generated by Django 4.1.2 on 2022-11-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="winner",
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
