# Generated by Django 4.1.2 on 2022-11-05 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_value", models.FloatField(blank=True, default=0.0)),
                ("odd", models.FloatField(blank=True, default=0.0)),
                ("team", models.CharField(max_length=120)),
                (
                    "winner",
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                (
                    "bet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bet_types",
                        to="bets.bet",
                    ),
                ),
            ],
        ),
    ]
