# Generated by Django 4.1.2 on 2022-11-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bets", "0001_initial"),
        ("bet_types", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bettype",
            name="bet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bet_types",
                to="bets.bet",
            ),
        ),
    ]
