# Generated by Django 4.1.2 on 2022-11-04 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("historys", "0002_alter_history_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
