# Generated by Django 4.1.2 on 2022-11-03 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Championship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("initial_date", models.DateField()),
                (
                    "e_sport",
                    models.CharField(
                        choices=[
                            ("League of Legends", "Leagueoflegends"),
                            ("Overwatch", "Overwatch"),
                            ("Counter Strike", "Counterstrike"),
                            ("Valorant", "Valorant"),
                            ("Is not in a championship", "Default"),
                        ],
                        default="Is not in a championship",
                        max_length=50,
                    ),
                ),
                ("winner", models.CharField(blank=True, max_length=50, null=True)),
                ("entry_amount", models.FloatField()),
                ("prize", models.FloatField()),
            ],
        ),
    ]
