# Generated by Django 4.1.2 on 2022-11-04 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("championships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="championship",
            name="staff_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="championships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
