# Generated by Django 4.1.2 on 2022-11-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="championship",
            name="entry_amount",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="championship",
            name="prize",
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="championship",
            name="staff_owner_id",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="championship",
            name="winner",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
