# Generated by Django 4.1.2 on 2022-11-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("championships", "0002_championship_entry_amount_championship_prize_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championship",
            name="staff_owner_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="championships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
