# Generated by Django 4.1.2 on 2022-11-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championships", "0003_alter_championship_staff_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championship",
            name="entry_amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="championship",
            name="prize",
            field=models.FloatField(),
        ),
    ]
