# Generated by Django 4.1.2 on 2022-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_game_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="initial_date",
            field=models.DateField(null=True),
        ),
    ]
