# Generated by Django 4.1.2 on 2022-11-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_initial_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="initial_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
